---
kind: pipeline
type: docker
name: release-latest

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: publish-docker-wopi-latest
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/wopiserver
    tags: latest
    dockerfile: wopiserver.Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    build_args:
      - VERSION=${DRONE_SEMVER_SHORT}-g${DRONE_COMMIT:0:7}
    custom_dns:
      - 128.142.17.5
      - 128.142.16.5

---
kind: pipeline
type: docker
name: release

platform:
  os: linux
  arch: amd64

trigger:
  event:
    include:
    - tag

steps:
- name: publish-docker-wopi-tag
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/wopiserver
    tags: ${DRONE_TAG}
    dockerfile: wopiserver.Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    build_args:
      - VERSION=${DRONE_TAG}
    custom_dns:
      - 128.142.17.5
      - 128.142.16.5

---
kind: pipeline
type: docker
name: release-xrootd

platform:
  os: linux
  arch: amd64

trigger:
  event:
    include:
    - tag

steps:
- name: publish-docker-wopi-tag
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/wopiserver
    tags: ${DRONE_TAG}-xrootd
    dockerfile: wopiserver-xrootd.Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    build_args:
      - VERSION=${DRONE_TAG}
    custom_dns:
      - 128.142.17.5
      - 128.142.16.5
