---
kind: pipeline
type: docker
name: release-latest

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: publish-docker-wopi-latest
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/wopiserver
    tags: latest
    dockerfile: wopiserver.Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password

---
kind: pipeline
type: docker
name: release

platform:
  os: linux
  arch: amd64

trigger:
  event:
    include:
    - tag

steps:
- name: publish-docker-wopi-tag
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/wopiserver
    tags: ${DRONE_TAG}
    dockerfile: wopiserver.Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
