#!/bin/sh

echo "${WOPISECRET:-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 12 | head -n 1)}" > /etc/wopi/wopisecret
#cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 12 | head -n 1 > /etc/wopi/wopisecret

echo "${OCSECRET:-password}" > /etc/wopi/ocsecret

/usr/bin/curl -o /etc/wopi/wopiserver.defaults.conf ${CONFIGURATION}/wopi/wopiserver.conf

/usr/bin/curl -o /etc/eos.keytab ${CONFIGURATION}/eos/eos.keytab

groupadd -g 48 apache
useradd -u 48 -g 48 -m apache

chown apache:apache /etc/eos.keytab
chmod 400 /etc/eos.keytab
chown -R apache:apache /etc/wopi

#exec /usr/bin/wopiserver.py

exec sudo -u apache python /usr/bin/wopiserver.py
