# docker-compose configuration file for WopiServer
#
# Build with:   docker-compose -f wopiserver.yaml build
# Run with:     docker-compose --project-name wopiserver -f wopiserver.yaml up -d
#
#
version: "3.3"
services:
  wopiserver:
    build:
      context: .
      dockerfile: wopiserver.Dockerfile
    image: wopiserver:cern
    container_name: wopiserver
    hostname: cbox-wopi-docker-01
    network_mode: "bridge"
    restart: always
    ports:
      - 8880:8880
    volumes:
      - wopi_config:/etc/wopi
      - wopi_logs:/var/log/wopi
      - wopi_storage:/var/wopi_local_storage
    healthcheck:
      test: ["CMD", "curl", "--insecure", "http://localhost:8880"]
      interval: 60s
      timeout: 5s
      retries: 3
      #start_period: 60s

volumes:
  wopi_logs:
  wopi_config:
  wopi_storage:
